### ISSUE TITLE
Decoupling from React

### ISSUE THREAD

**Issue by amireh** [philcockfield/react-schema#7]
I would really like to be able to use this outside of the domain of React codebases. This could be very useful in plain nodejs contexts or backend tools.

What are your thoughts on decoupling from React? We already require people to use our own decorated PropTypes to gain introspection capabilities, so it wouldn't be _too much_ out there to roll our own checkers and get rid of the dependency.

Heck, if it's really a big deal, we can let people inject the base PropTypes that we use (if they're using React, then that would be `React.PropTypes`) and then we provide an external plugin that provides non-React PropTypes which others can use if they're not using React.

**Comment by eliot-akira** [comment]
Calling PropTypes directly for validation will be deprecated in a future version of React: https://fb.me/react-warning-dont-call-proptypes

In the article, they mention a couple of stand-alone implementations of PropTypes: [1](https://github.com/developit/proptypes), [2](https://github.com/aackerman/PropTypes)

It makes sense to use dependency injection to decouple this library from React's PropTypes.

**Comment by eliot-akira** [comment]
For what it's worth, I created forks of `React.PropTypes` and `react-schema` that are decoupled from React, and wrote an opinionated implementation called [`proptypes-schema`](https://github.com/eliot-akira/proptypes-schema).

**Comment by philcockfield** [comment]
Fantastic @eliot-akira.

**Comment by philcockfield** [comment]
Decoupling from React, given the moves they've recently made on this, is great.  Not sure what to do with this library now - it's basically unusable with the latest release(s) of React.

**Comment by eliot-akira** [comment]
I think the concept of react-schema is great, to extend React.PropTypes and make it useful for purposes like an interactive components explorer/sandbox  (trying props combinations), and automatically testing components with appropriate prop types.

The stand-alone forks of React.PropTypes mentioned in Facebook's article are OK but outdated. I used this one (https://github.com/developit/proptypes) because it covers almost all the prop types in the original. It's a drop-in replacement, so you might could use it to make react-schema independent of React.

It would be great if there was a well-tested, up-to-date and stand-alone fork of React.PropTypes, which you could integrate with react-schema.

**Comment by philcockfield** [comment]
Implemented by @eliot-akira (PR #8) and released as `2.0.0`.  Thanks @eliot-akira.
